name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Create MCP config directory
        run: |
          mkdir -p .cursor

      - name: Create MCP config file
        run: |
          echo '{
            "mcpServers": {
              "mcp-atlassian": {
                "command": "python",
                "args": ["-m", "mcp_atlassian.server"]
              }
            }
          }' > .cursor/mcp.json

      - name: Install mcp-atlassian in development mode
        run: |
          uv pip install -e .

      - name: Run Atlassian tests
        run: |
          python src/mcp_atlassian/test_mcp_atlassian.py
